import { LiveQueryProvider } from '@sanity/preview-kit'
import { getClient } from 'lib/sanity.client'
import { useState } from 'react'

export default function PreviewProvider({
  children,
  perspective,
  token,
}: {
  children: React.ReactNode
  perspective: string | null
  token: string
}) {
  // Build the preview client with the draft token so Sanity's stega payloads
  // are generated by the same client configuration used for the live query.
  // Calling `withConfig({stega: true})` on a published client can produce
  // malformed markers that the visual-editing parser cannot decode.
  const [client] = useState(() =>
    getClient({
      token,
      perspective: perspective || 'drafts',
    }),
  )
  return (
    <LiveQueryProvider
      client={client}
      perspective={
        typeof perspective === 'string' ? perspective.split(',') : undefined
      }
      token={token}
    >
      {children}
    </LiveQueryProvider>
  )
}
